"""Immutable deterministic authorization for NEST AuthZ."""

from .domain import (
    Action,
    ApprovalRequirement,
    Authority,
    AuthorityApplicabilityResult,
    AuthorityApplicabilityStatus,
    AuthorityBoundEvaluation,
    AuthorityGrant,
    AuthorityScope,
    AuthorityValidationResult,
    AuthorityValidationStatus,
    AuthorizationRequest,
    AuthorizationState,
    Condition,
    ConditionOperator,
    ConditionStatus,
    Decision,
    DecisionEvidence,
    DelegationChain,
    Obligation,
    Outcome,
    FieldNamespace,
    FieldReference,
    Policy,
    PolicyBundle,
    Principal,
    Reason,
    RequestContext,
    Resource,
    Rule,
    RuleEffect,
    RuleEvaluation,
    RuleEvaluationStatus,
    RevocationSet,
    Sha256Digest,
    Subject,
    VerifiedAuthority,
)
from .applicability import check_authority_applicability
from .canonical import canonical_bytes, sha256_digest
from .delegation import AuthorityValidationError, validate_authority
from .evaluator import EvaluationError, evaluate

__all__ = [
    "Action",
    "ApprovalRequirement",
    "Authority",
    "AuthorityApplicabilityResult",
    "AuthorityApplicabilityStatus",
    "AuthorityBoundEvaluation",
    "AuthorityGrant",
    "AuthorityScope",
    "AuthorityValidationError",
    "AuthorityValidationResult",
    "AuthorityValidationStatus",
    "AuthorizationRequest",
    "AuthorizationState",
    "Condition",
    "ConditionOperator",
    "ConditionStatus",
    "Decision",
    "DecisionEvidence",
    "DelegationChain",
    "Obligation",
    "Outcome",
    "FieldNamespace",
    "FieldReference",
    "Policy",
    "PolicyBundle",
    "Principal",
    "Reason",
    "RequestContext",
    "Resource",
    "Rule",
    "RuleEffect",
    "RuleEvaluation",
    "RuleEvaluationStatus",
    "RevocationSet",
    "Sha256Digest",
    "Subject",
    "VerifiedAuthority",
    "canonical_bytes",
    "check_authority_applicability",
    "EvaluationError",
    "evaluate",
    "sha256_digest",
    "validate_authority",
]
